import archerPng from './sprites/archer.png';
import archerJson from './sprites/archer.json';
import boarPng from './sprites/boar.png';
import boarJson from './sprites/boar.json';
import skeletonPng from './sprites/skeleton.png';
import skeletonJson from './sprites/skeleton.json';
import boarAlphaPng from './sprites/boar_alpha.png';
import boarAlphaJson from './sprites/boar_alpha.json';
import elvenPng from './sprites/elven.png';
import elvenJson from './sprites/elven.json';
import magePng from './sprites/mage.png';
import mageJson from './sprites/mage.json';
import knightPng from './sprites/knight.png';
import knightJson from './sprites/knight.json';
import classFxPng from './sprites/classfx.png';
import classFxJson from './sprites/classfx.json';
import townPng from './sprites/town.png';
import townJson from './sprites/town.json';
import itemsPng from './sprites/items.png';
import itemsJson from './sprites/items.json';
import rangerFxPng from './sprites/rangerfx.png';
import rangerFxJson from './sprites/rangerfx.json';
import aurasPng from './sprites/auras.png';
import aurasJson from './sprites/auras.json';

/** Sprite atlases generated by tools/slice_sheet.py from the sheets in art-source/. */
export const ATLASES = [
  { key: 'archer', png: archerPng, json: archerJson },
  { key: 'boar', png: boarPng, json: boarJson },
  { key: 'skeleton', png: skeletonPng, json: skeletonJson },
  { key: 'boar_alpha', png: boarAlphaPng, json: boarAlphaJson },
  { key: 'elven', png: elvenPng, json: elvenJson },
  { key: 'mage', png: magePng, json: mageJson },
  { key: 'knight', png: knightPng, json: knightJson },
  { key: 'classfx', png: classFxPng, json: classFxJson },
  { key: 'town', png: townPng, json: townJson },
  { key: 'items', png: itemsPng, json: itemsJson },
  { key: 'rangerfx', png: rangerFxPng, json: rangerFxJson },
  { key: 'auras', png: aurasPng, json: aurasJson },
] as const;

/** Single images (none at the moment: every sprite lives in an atlas). */
export const IMAGES: ReadonlyArray<{ key: string; png: string }> = [];
