import archerPng from './sprites/archer.png';
import archerJson from './sprites/archer.json';
import boarPng from './sprites/boar.png';
import boarJson from './sprites/boar.json';
import skeletonPng from './sprites/skeleton.png';
import skeletonJson from './sprites/skeleton.json';
import boarAlphaPng from './sprites/boar_alpha.png';
import boarAlphaJson from './sprites/boar_alpha.json';
import elvenPng from './sprites/elven.png';
import elvenJson from './sprites/elven.json';
import itemsPng from './sprites/items.png';
import itemsJson from './sprites/items.json';
import magicPng from './sprites/magic.png';
import magicJson from './sprites/magic.json';
import skyPng from './sprites/sky.png';
import skyJson from './sprites/sky.json';
import arrowPng from './sprites/arrow.png';

/** Sprite atlases generated by tools/slice_sheet.py from the sheets in art-source/. */
export const ATLASES = [
  { key: 'archer', png: archerPng, json: archerJson },
  { key: 'boar', png: boarPng, json: boarJson },
  { key: 'skeleton', png: skeletonPng, json: skeletonJson },
  { key: 'boar_alpha', png: boarAlphaPng, json: boarAlphaJson },
  { key: 'elven', png: elvenPng, json: elvenJson },
  { key: 'items', png: itemsPng, json: itemsJson },
  { key: 'magic', png: magicPng, json: magicJson },
  { key: 'sky', png: skyPng, json: skyJson },
] as const;

export const IMAGES = [{ key: 'arrow', png: arrowPng }] as const;
